openapi: 3.0.1
info:
  title: ServiceBAPI
  description: API Definition of ServiceBAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/serviceb
paths:
  /accountInquiry:
    get:
      responses:
        default:
          description: Default response
  /accountInquiryWithQuery/{accountNumber}:
    get:
      parameters:
      - name: accountNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
